# GitLab CI Docker Image
image: node:6.11.0
# Build - Build necessary JS files
# Test - Run tests
# Deploy - Deploy application to S3/ElasticBeanstalk
stages:
  - build
  - test
  - deploy
# Configuration

# Job: Build
# Installs npm packages, transpiles ES6 -> ES5
# Passes node_modules/, dist/ onto next steps using artifacts
# build:
#   stage: build
#   script:
#     - npm install
#     - ./bin/build
#   artifacts:
#     paths:
#       - node_modules/
#       - dist/
#   tags:
#     - nodejs-app
# Job: Test
# Run tests against our application
# If this fails, we do not deploy
test:
  stage: test
  script:
    - mocha test/bootstrap.test.js
  tags:
    - nodejs-app
# Job: Deploy
# Zips the contents of our built application, uploads to S3
# Configures a new EB version and switches to that version
# deploy:
#   stage: deploy
#   script:
#     - ./bin/deploy
#   tags:
#     - nodejs-app
